#gpu_factor: 4
batch_size: 32
#batch_size_cuda = batch_size * gpu_factor
batch_size_cuda: 128
#seq_len: 16384
seq_len: 4096
#seq_len_cuda = seq_len * gpu_factor
seq_len_cuda: 16384
win_len: 256
step: 1
n_epochs: 500
wd: 0.0001
max_lr: 0.001
betas: [0.9, 0.99]
net_type: lstm
save_path: ./outputs/lstm_out
load_path: 
log_interval: 100
save_interval: 100
d: 0.2
#augs: ['flip', cutout]
augs: