seq_len: 16384
win_len: 256
step: 1
batch_size: 128
n_epochs: 3000
wd: 0.0001
max_lr: 0.001
betas: [0.9, 0.99]
net_type: lstm
save_path: ./outputs/lstm_out
load_path: 
log_interval: 100
save_interval: 100
d: 0.2
augs: ['flip', cutout]