#seq_len: 16384
seq_len: 4096
#seq_len_cuda = seq_len * gpu_factor
seq_len_cuda: 16384
win_len: 256
step: 1
#gpu_factor: 4
batch_size: 32
#batch_size_cuda = batch_size * gpu_factor
batch_size_cuda: 128
n_epochs: 1000
#n_epochs: 5
wd: 0.00001
max_lr: 0.001
betas: [0.9, 0.99]
net_type: cnn_lstm

save_path: ./outputs
#load_path: ./outputs/cnn_lstm
load_path:
log_interval: 100
save_interval: 100
d:
- 0.2
#d: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
augs: